//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkt()
        {
            this.PozycjaZamowienie = new HashSet<PozycjaZamowienie>();
        }
    
        public long Id { get; set; }
        public string Nazwa { get; set; }
        public int Ilosc { get; set; }
        public bool Dostepny { get; set; }
        public decimal Cena { get; set; }
        public System.DateTime DataDodania { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaZamowienie> PozycjaZamowienie { get; set; }
    }
}
